const StockController = require("./Controllers/StockController")
const ProductController = require("./Controllers/ProductController")
const EntriesController = require("./Controllers/EntriesController")
const ServiceController = require("./Controllers/ServiceController")
const StatisticsController = require("./Controllers/StatisticsController")
const UsersController = require("./Controllers/UsersController")
const express = require("express")
const app = express()

app.use(StockController)
app.use(ProductController)
app.use(EntriesController)
app.use(ServiceController)
app.use(StatisticsController)
app.use(UsersController)
app.listen(3000, () => console.log("API ON"))