const StockController = require("./Controllers/StockController")
const ProductController = require("./Controllers/ProductController")
const EntriesController = require("./Controllers/EntriesController")
// const StatisticsController = require("./Controllers/StatisticsController")
const express = require("express")
const app = express()

app.use(StockController)
app.use(ProductController)
app.use(EntriesController)
// app.use(StatisticsController)
app.listen(3000, ()=> console.log("API ON"))